/** Real Surge HTTP API endpoints (verified: https://surge.mitsea.com/others/http-api.md). */
export const ENDPOINTS = {
  featuresMitm: "/v1/features/mitm",
  featuresCapture: "/v1/features/capture",
  featuresRewrite: "/v1/features/rewrite",
  featuresScripting: "/v1/features/scripting",
  outbound: "/v1/outbound",
  outboundGlobal: "/v1/outbound/global",
  policies: "/v1/policies",
  policyDetail: "/v1/policies/detail",
  policiesTest: "/v1/policies/test",
  policyGroups: "/v1/policy_groups",
  policyGroupsTestResults: "/v1/policy_groups/test_results",
  policyGroupsSelect: "/v1/policy_groups/select",
  policyGroupsTest: "/v1/policy_groups/test",
  requestsRecent: "/v1/requests/recent",
  requestsActive: "/v1/requests/active",
  requestsKill: "/v1/requests/kill",
  profilesCurrent: "/v1/profiles/current",
  profilesReload: "/v1/profiles/reload",
  dns: "/v1/dns",
  dnsFlush: "/v1/dns/flush",
  dnsDelayTest: "/v1/test/dns_delay",
  modules: "/v1/modules",
  scripting: "/v1/scripting",
  scriptingEvaluate: "/v1/scripting/evaluate",
  scriptingCronEvaluate: "/v1/scripting/cron/evaluate",
  events: "/v1/events",
  rules: "/v1/rules",
  traffic: "/v1/traffic",
  metrics: "/v1/metrics",
} as const;
